### ISSUE TITLE
Only static is output when audio is being played

### ISSUE THREAD

**Issue by JosephDuffy** [geneccx/XonarSTDeluxeDriver#3]
Firstly, thanks for the making this! Getting this soundcard working is the last piece of the puzzle for me :)

Whenever I play any sound I get a loud static noise. I have turned the volume now to around 20% and recorded the sound with my phone: https://www.dropbox.com/s/n4f9cl5alsslbst/Soundcard%20Sound.m4a?dl=0

I will note that switching the output does produce the audible click that the soundcard makes when switching inputs. The same sound is heard when (un)muting.

To install I ran Product > Archive and then exported the kext from the archive. I installed the kext using Kext Wizard. I am on macOS 10.12.4 with a Xonar Essence STX. Using VoodooHDA I have working sound from my motherboard.

**Comment by geneccx** [comment]
I recall having a similar issue, and I think it had to do with the system definitions. Are you using the system definitions for a Mac Pro?

Try playing around with it a bit, I'm using iMac14,2 and it seems to work.

The only other thing I can think of if this doesn't work is the output format. You should be able to change this with "Audio Midi Setup.app".

**Comment by JosephDuffy** [comment]
I was using iMac17,1, but it appears that iMac 14,2 works, thanks! ❤️

**Comment by athre0z** [comment]
For reference: `MacPro6,1` is working fine as well.

**Comment by geneccx** [comment]
Thanks. I'm going to add a troubleshooting section in the readme for any people who might encounter the same issue in the future.
